from typing import Optional, Any, Dict
from typing_extensions import TypedDict

class GuardianResult(TypedDict, total=False):
    approved: bool
    isCorrect: bool
    isGrounded: bool
    reason: str

class SupportState(TypedDict, total=False):
    threadId: str
    userMessage: str
    intent: Optional[str]                    # "order_status" | "refund" | "general_inquiry"
    orderId: Optional[str]                   # e.g., "ORD-1001"
    toolResult: Optional[Dict[str, Any]]     # Output of getOrder / checkRefundEligibility / getOrderStatus
    requiresApproval: Optional[bool]         # Set to True when human supervisor authorization is required
    approvalStatus: Optional[str]            # "pending" | "approved" | "rejected"
    actionResult: Optional[Dict[str, Any]]   # Result of executing sensitive operation (executeRefund)
    draftResponse: Optional[str]             # Candidate response generated by LLM
    guardianResult: Optional[GuardianResult] # Quality/grounding evaluation by JEV Guardian LLM
    guardianAttempts: Optional[int]          # Retry count for JEV Guardian (max 2)
    finalResponse: Optional[str]             # Final approved response returned to user
    status: Optional[str]                    # "in_progress" | "waiting_for_approval" | "completed" | "rejected"
