from typing import Optional, Any, Dict
from typing_extensions import TypedDict

class GuardrailResult(TypedDict, total=False):
    safe: bool
    reason: Optional[str]

class SupportState(TypedDict, total=False):
    threadId: str
    userMessage: str
    isSafe: Optional[bool]                   # True if passed input guardrails, False if rejected
    guardrailResult: Optional[GuardrailResult] # Evaluation details from input guardrail
    intent: Optional[str]                    # "order_status" | "refund" | "general_inquiry"
    orderId: Optional[str]                   # e.g., "ORD-1001"
    toolResult: Optional[Dict[str, Any]]     # Output of getOrder / checkRefundEligibility / getOrderStatus
    requiresApproval: Optional[bool]         # Set to True when human supervisor authorization is required
    approvalStatus: Optional[str]            # "pending" | "approved" | "rejected"
    actionResult: Optional[Dict[str, Any]]   # Result of executing sensitive operation (executeRefund)
    draftResponse: Optional[str]             # Candidate response generated by LLM
    finalResponse: Optional[str]             # Final response returned to user
    status: Optional[str]                    # "in_progress" | "waiting_for_approval" | "completed" | "rejected"
